services:
  gateway:
    build: services/gateway/
    container_name: gateway
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - INGESTION_URL=http://ingestion:8001
      - QUERY_URL=http://query:8002
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - ollama
      - ingestion
      - query

  ingestion:
    build: services/ingestion/
    container_name: ingestion
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
    expose:
      - "8001"
    volumes:
      - ./data:/app/data:ro
    depends_on:
      - qdrant
      - ollama

  query:
    build: services/query/
    container_name: query
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
    expose:
      - "8002"
    depends_on:
      - qdrant
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /bin/ollama serve &
        sleep 5
        ollama pull llama3.2:3b
        ollama pull nomic-embed-text
        wait

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  ollama-data:
  qdrant-data:

