apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  namespace: doc-assist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doc-assist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doc-assist
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
        volumeMounts:
          - name: qdrant-storage
            mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc
