apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: doc-assist
spec:
  selector:
    app.kubernetes.io/name: doc-assist
    app.kubernetes.io/component: ingestion
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
