apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  namespace: doc-assist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doc-assist
      app.kubernetes.io/component: query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doc-assist
        app.kubernetes.io/component: query
    spec:
      containers:
      - name: query
        image: query:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: doc-assist-config
