apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: doc-assist
spec:
  template:
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: doc-assist
spec:
  template:
    spec:
      containers:
        - name: ingestion
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  namespace: doc-assist
spec:
  template:
    spec:
      containers:
        - name: query
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: doc-assist
spec:
  template:
    spec:
      containers:
        - name: ollama
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "6Gi"
              cpu: "500m"
            limits:
              memory: "7Gi"
              cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  namespace: doc-assist
spec:
  template:
    spec:
      containers:
        - name: qdrant
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: doc-assist
spec:
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: doc-assist
spec:
  storageClassName: managed-csi
