apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: doc-assist
spec:
  selector:
    app.kubernetes.io/name: doc-assist
    app.kubernetes.io/component: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
