apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: doc-assist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doc-assist
      app.kubernetes.io/component: ingestion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doc-assist
        app.kubernetes.io/component: ingestion
    spec:
      containers:
      - name: ingestion
        image: ingestion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: doc-assist-config
